<?php if (null !== $block->getWebsiteId()): ?>
<script>
    const crispPluginURL = "https://plugins.crisp.chat/urn:crisp.im:magento:0"
    let isHyva = false;
    
    if (<?= $escaper->escapeHtml($block->isHyva()); ?> == 1) {
        isHyva = true;
    }

    window.$crisp = [];
    window.CRISP_WEBSITE_ID = "<?= $escaper->escapeHtml($block->getWebsiteId()); ?>";
    (function () {
        d = document;
        s = d.createElement("script");
        s.src = "https://client.crisp.chat/l.js";
        s.async = 1;
        d.getElementsByTagName("head")[0].appendChild(s);
    })();

    window.CRISP_READY_TRIGGER = function () {
        let _customerId =  "<?= $escaper->escapeHtml($block->getCustomerId()); ?>"
        let _customerEmail = "<?= $escaper->escapeHtml($block->getCustomerEmail()); ?>"
        window.CRISP_SESSION_ID = $crisp.get('session:identifier');

        $crisp.push(['set', 'session:segments', [['magento']]]);

        if (_customerEmail) {
            $crisp.push(['set', 'user:email', _customerEmail]);
        }

        if (_customerId) {
            postData("customer", {id: parseInt(_customerId)})
        }

        if (!isHyva) {
            postCartLuma();
        }
    }

    function postCartLuma() {
        require(["Magento_Customer/js/customer-data"], (customerData) => {
            setTimeout(() => {
                let _cartType = "cart"
                let _cart = customerData.get("cart");
                let _customer = customerData.get("customer");
                let _cartData = _cart()
                let _customerData = _customer()
                let _currency = "<?= $escaper->escapeHtml($block->getCurrentCurrency()); ?>"

                if ((_customerData || {}).fullname) {
                    $crisp.push(['set', 'user:nickname', _customerData.fullname]);
                }

                if ((_cartData || {}).items) {

                    if (_currency !== null) {
                        _cartData.currency = _currency
                    }

                    postData(_cartType, _cartData);
                }

                _cart.subscribe((data) => {
                    if (_currency !== null) {
                        data.currency = _currency
                    }

                    postData(_cartType, data);
                });
            }, 200);
        })
    }

    function postCartHyva(data) {
        let _cartType = "cart"
        let _customer = data?.detail?.data.customer || null;
        let _cart = data?.detail?.data.cart || null;
        let _currency = "<?= $escaper->escapeHtml($block->getCurrentCurrency()); ?>"

        if (_customer?.fullname) {
            $crisp.push(['set', 'user:nickname', _customer.fullname]);
        }

        if (_cart?.items) {
            if (_currency !== null) {
                _cart.currency = _currency
            }

            // Only post cart session ID exists
            if (window.CRISP_SESSION_ID) {
                postData(_cartType, _cart);
            }
        }
    }

    function postData(type, body) {
        fetch(
                crispPluginURL +
                "/visitors/website/" +
                window.CRISP_WEBSITE_ID +
                "/session/" +
                window.CRISP_SESSION_ID +
                "/" + type,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Accept: "application/json",
                },
                body: JSON.stringify(body),
            }
        );
    }

    if (isHyva) {
        window.addEventListener("private-content-loaded", postCartHyva);
    }
</script>
<?php else: ?>
<script>
    console.warn(
        `Crisp chatbox is installed but not configured -
        To enable the chatbox please login to your store as
        admin then go to: Stores > Settings > Configuration
        > Crisp > Settings and configure your Crisp websiteID.`
    );
</script>
<?php endif; ?>
