<?php if (null !== $block->getWebsiteId()): ?>
<script>
    const crispPluginURL = "https://plugins.crisp.chat/urn:crisp.im:magento:0"

    window.$crisp = [];
    window.CRISP_WEBSITE_ID = "<?= $escaper->escapeHtml($block->getWebsiteId()); ?>";
    (function () {
        d = document;
        s = d.createElement("script");
        s.src = "https://client.crisp.chat/l.js";
        s.async = 1;
        d.getElementsByTagName("head")[0].appendChild(s);
    })();

    window.CRISP_READY_TRIGGER = function () {
        let _customerId =  "<?= $escaper->escapeHtml($block->getCustomerId()); ?>"
        let _customerEmail = "<?= $escaper->escapeHtml($block->getCustomerEmail()); ?>"
        window.CRISP_SESSION_ID = $crisp.get('session:identifier');

        // Set session segment (only after first message is sent)
        $crisp.push(["on", "message:sent", () => {
          $crisp.push(["set", "session:segments", [["magento"]]]);
          $crisp.push(["off", "message:sent"]);
        }]);

        if (_customerEmail) {
            $crisp.push(['set', 'user:email', _customerEmail]);
        }

        if (_customerId) {
            postData("customer", {id: parseInt(_customerId)})
        }

        postCartLuma();
    }

    function postCartLuma() {
        require(["Magento_Customer/js/customer-data"], (customerData) => {
            setTimeout(() => {
                let _cartType = "cart"
                let _cart = customerData.get("cart");
                let _customer = customerData.get("customer");
                let _cartData = _cart()
                let _customerData = _customer()
                let _currency = "<?= $escaper->escapeHtml($block->getCurrentCurrency()); ?>"

                if ((_customerData || {}).fullname) {
                    $crisp.push(['set', 'user:nickname', _customerData.fullname]);
                }

                if (_cartData?.items?.length > 0) {

                    if (_currency !== null) {
                        _cartData.currency = _currency
                    }

                    postData(_cartType, _cartData);
                }

                _cart.subscribe((data) => {
                    if (_currency !== null) {
                        data.currency = _currency
                    }

                    postData(_cartType, data);
                });
            }, 200);
        })
    }

    function postData(type, body) {
        fetch(
                crispPluginURL +
                "/visitors/website/" +
                window.CRISP_WEBSITE_ID +
                "/session/" +
                window.CRISP_SESSION_ID +
                "/" + type,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Accept: "application/json",
                },
                body: JSON.stringify(body),
            }
        );
    }
</script>
<?php else: ?>
<script>
    console.warn(
        `Crisp chatbox is installed but not configured -
        To enable the chatbox please login to your store as
        admin then go to: Stores > Settings > Configuration
        > Crisp > Settings and configure your Crisp websiteID.`
    );
</script>
<?php endif; ?>
